//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class asistencia
    {
        public int id_asistencia { get; set; }
        public Nullable<int> id_clase { get; set; }
        public Nullable<int> id_persona { get; set; }
    
        public virtual clase clase { get; set; }
        public virtual personas personas { get; set; }
    }
}
