//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class prueba_pabloEntities : DbContext
    {
        public prueba_pabloEntities()
            : base("name=prueba_pabloEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<asistencia> asistencia { get; set; }
        public virtual DbSet<categoria_torneo> categoria_torneo { get; set; }
        public virtual DbSet<clase> clase { get; set; }
        public virtual DbSet<club> club { get; set; }
        public virtual DbSet<direcciones> direcciones { get; set; }
        public virtual DbSet<dominante> dominante { get; set; }
        public virtual DbSet<estado_clase> estado_clase { get; set; }
        public virtual DbSet<personas> personas { get; set; }
        public virtual DbSet<personas_torneos> personas_torneos { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<sedes> sedes { get; set; }
        public virtual DbSet<tipo_documento> tipo_documento { get; set; }
        public virtual DbSet<tipo_torneo> tipo_torneo { get; set; }
        public virtual DbSet<torneo> torneo { get; set; }
    }
}
