//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class personas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personas()
        {
            this.asistencia = new HashSet<asistencia>();
            this.personas_torneos = new HashSet<personas_torneos>();
        }
    
        public int id_persona { get; set; }
        public int id_rol { get; set; }
        public int id_club { get; set; }
        public int id_ojo_dominante { get; set; }
        public int id_lado_dominante { get; set; }
        public int id_tipo_doc { get; set; }
        public int id_direcciones { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string nro_doc { get; set; }
        public int federado { get; set; }
        public string observaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asistencia> asistencia { get; set; }
        public virtual club club { get; set; }
        public virtual direcciones direcciones { get; set; }
        public virtual dominante dominante { get; set; }
        public virtual dominante dominante1 { get; set; }
        public virtual rol rol { get; set; }
        public virtual tipo_documento tipo_documento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personas_torneos> personas_torneos { get; set; }
    }
}
