//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class personas_torneos
    {
        public int id_personas_torneos { get; set; }
        public Nullable<int> id_torneo { get; set; }
        public Nullable<int> id_persona { get; set; }
        public Nullable<int> id_cat_tor { get; set; }
        public Nullable<int> puntaje { get; set; }
        public Nullable<int> posicion { get; set; }
    
        public virtual categoria_torneo categoria_torneo { get; set; }
        public virtual personas personas { get; set; }
        public virtual torneo torneo { get; set; }
    }
}
